cmd_drivers/net/wireless/dhd/danil_e71_log.o := /home/danil_e71/android-ndk/toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/bin/arm-eabi-gcc -Wp,-MD,drivers/net/wireless/dhd/.danil_e71_log.o.d  -nostdinc -isystem /home/danil_e71/android-ndk/toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/bin/../lib/gcc/arm-eabi/4.4.0/include -I/home/danil_e71/android-ndk/toolchains/huawei_u8850_kernel_ics-master/arch/arm/include -Iinclude  -include include/generated/autoconf.h -D__KERNEL__ -mlittle-endian -Iarch/arm/mach-msm/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -Werror -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -Os -marm -mabi=aapcs-linux -mno-thumb-interwork -funwind-tables -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -Wframe-larger-than=1024 -fno-stack-protector -fomit-frame-pointer -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DLINUX -DBCMDRIVER -DBCMDONGLEHOST -DDHDTHREAD -DBCMWPA2 -DBCMWAPI_WPI -DUNRELEASEDCHIP -DSRCBASE=\"/home/danil_e71/android-ndk/toolchains/huawei_u8850_kernel_ics-master/../..\" -DCONFIG_WIRELESS_EXT -DDHD_GPL -DDHD_SCHED -DDHD_DEBUG -DSDTEST -DBDC -DTOE -DDHD_BCMEVENTS -DSHOW_EVENTS -DSDIO_ISR_THREAD -DEMBEDDED_PLATFORM -DBCMSDIO -DDHD_GPL -DBCMLXSDMMC -DBCMPLATFORM_BUS -Idrivers/net/wireless/dhd -Idrivers/net/wireless/dhd/include  -DMODULE -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(danil_e71_log)"  -D"KBUILD_MODNAME=KBUILD_STR(dhd)" -D"DEBUG_HASH=38" -D"DEBUG_HASH2=25" -c -o drivers/net/wireless/dhd/danil_e71_log.o drivers/net/wireless/dhd/danil_e71_log.c

deps_drivers/net/wireless/dhd/danil_e71_log.o := \
  drivers/net/wireless/dhd/danil_e71_log.c \
  drivers/net/wireless/dhd/danil_e71_log.h \

drivers/net/wireless/dhd/danil_e71_log.o: $(deps_drivers/net/wireless/dhd/danil_e71_log.o)

$(deps_drivers/net/wireless/dhd/danil_e71_log.o):
